# Generated by Django 5.2.8 on 2025-12-23 05:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('name', models.CharField(max_length=64, verbose_name='회의실')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='설명')),
                ('seat_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='좌석수')),
                ('capacity_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(999)], verbose_name='수용수')),
                ('has_monitor', models.BooleanField(default=True, verbose_name='화면공유')),
                ('has_microphone', models.BooleanField(default=True, verbose_name='마이크')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
