# Generated by Django 5.2.8 on 2025-12-23 05:32

import common.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservation_attendee_set', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '참석자',
                'verbose_name_plural': '참석자 목록',
                'db_table': 'reservations_attendee',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('description', models.CharField(blank=True, max_length=1024, null=True, verbose_name='설명')),
                ('start_datetime', models.DateTimeField(verbose_name='시작 시간')),
                ('end_datetime', models.DateTimeField(verbose_name='종료 시간')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('attendees', models.ManyToManyField(related_name='reservations', through='reservations.Attendee', through_fields=('reservation', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='참석자')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservations', to='rooms.room', verbose_name='회의실')),
            ],
            options={
                'verbose_name': '예약',
                'verbose_name_plural': '예약 목록',
                'db_table': 'reservations_reservation',
            },
            bases=(models.Model, common.mixins.PrefetchValidationMixin),
        ),
        migrations.AddField(
            model_name='attendee',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='reservation_attendee_set', to='reservations.reservation', verbose_name='예약'),
        ),
        migrations.AddIndex(
            model_name='reservation',
            index=models.Index(fields=['room', 'start_datetime'], name='idx_reservation_01'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('reservation', 'user')},
        ),
    ]
