# Generated by Django 5.2.8 on 2025-12-31 00:36
from django.contrib.postgres.operations import TrigramExtension

import common.mixins
import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import meetings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reservations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        TrigramExtension(),
        migrations.CreateModel(
            name='Attendee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meeting_attendee_set', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
            options={
                'verbose_name': '참석자',
                'verbose_name_plural': '참석자 목록',
                'db_table': 'meetings_attendee',
            },
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('RESERVATION', '예약 회의'), ('STANDALONE', '일반 회의')], default='STANDALONE', max_length=16, verbose_name='회의 유형')),
                ('title', models.CharField(max_length=128, verbose_name='제목')),
                ('memo', models.TextField(blank=True, max_length=1024, null=True, verbose_name='메모')),
                ('minutes_content', models.TextField(blank=True, null=True, verbose_name='회의록 내용')),
                ('start_datetime', models.DateTimeField(default=django.utils.timezone.now, verbose_name='시작 시간')),
                ('end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='종료 시간')),
                ('is_open', models.BooleanField(default=False, verbose_name='공개여부')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('attendees', models.ManyToManyField(related_name='meetings', through='meetings.Attendee', through_fields=('meeting', 'user'), to=settings.AUTH_USER_MODEL, verbose_name='참석자')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('reservation', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='meeting', to='reservations.reservation', verbose_name='예약')),
            ],
            options={
                'verbose_name': '회의',
                'verbose_name_plural': '회의 목록',
                'db_table': 'meetings_meeting',
            },
            bases=(models.Model, common.mixins.PrefetchValidationMixin),
        ),
        migrations.AddField(
            model_name='attendee',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='meeting_attendee_set', to='meetings.meeting', verbose_name='예약'),
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('content_type', models.CharField(blank=True, max_length=128, verbose_name='파일종류')),
                ('upload_file', models.FileField(blank=True, null=True, upload_to=meetings.models.get_recording_upload_path, verbose_name='업로드 파일')),
                ('upload_file_size', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='업로드 파일 크기')),
                ('upload_file_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='업로드 파일 명')),
                ('webm_file', models.FileField(blank=True, max_length=256, null=True, upload_to=meetings.models.get_recording_upload_path, verbose_name='webm 파일')),
                ('webm_file_size', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='webm 파일 크기')),
                ('play_millisecond', models.IntegerField(default=0, verbose_name='재생 밀리초')),
                ('is_active', models.BooleanField(default=True, verbose_name='사용여부')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='meetings.meeting', verbose_name='회의')),
            ],
            options={
                'verbose_name': '녹음',
                'verbose_name_plural': '녹음 목록',
                'db_table': 'meetings_recording',
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('speaker_label', models.CharField(max_length=64, verbose_name='화자 레이블')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.meeting', verbose_name='회의')),
                ('original_recording', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='meetings.recording', verbose_name='원본 녹음')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL, verbose_name='매핑된 사용자')),
            ],
            options={
                'verbose_name': '화자',
                'verbose_name_plural': '화자 목록',
                'db_table': 'meetings_speaker',
            },
        ),
        migrations.CreateModel(
            name='SpeechRecognition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('task_id', models.CharField(max_length=32, verbose_name='작업 id')),
                ('speech_recognition_model_name', models.CharField(max_length=64, verbose_name='음성 인식 모델 이름')),
                ('align_model_name', models.CharField(max_length=64, verbose_name='정렬 모델 이름')),
                ('diarization_model_name', models.CharField(max_length=64, verbose_name='화자 분리 모델 이름')),
                ('task_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='작업 시작 시간')),
                ('speech_recognition_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='음성 인식 종료 시간')),
                ('align_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='정렬 종료 시간')),
                ('diarization_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='화자 분리 종료 시간')),
                ('assignment_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='할당 종료 시간')),
                ('task_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='작업 종료 시간')),
                ('task_step_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='작업 단계 코드')),
                ('task_status_code', models.CharField(max_length=16, verbose_name='작업 상태 코드')),
                ('language_code', models.CharField(blank=True, max_length=2, null=True, verbose_name='언어 코드')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('recording', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='speech_recognition_set', to='meetings.recording', verbose_name='녹음')),
            ],
            options={
                'verbose_name': '음성 인식',
                'verbose_name_plural': '음성 인식 목록',
                'db_table': 'meetings_speech_recognition',
            },
        ),
        migrations.CreateModel(
            name='Segment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('text', models.TextField(verbose_name='문자')),
                ('start_millisecond', models.IntegerField(blank=True, null=True, verbose_name='시작 밀리초')),
                ('end_millisecond', models.IntegerField(blank=True, null=True, verbose_name='종료 밀리초')),
                ('corrected_text', models.TextField(blank=True, null=True, verbose_name='교정된 문자')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.speaker', verbose_name='화자')),
                ('speech_recognition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.speechrecognition', verbose_name='음성 인식')),
            ],
            options={
                'verbose_name': '부분',
                'verbose_name_plural': '부분 목록',
                'db_table': 'meetings_segment',
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='latest_speech_recognition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='meetings.speechrecognition', verbose_name='최근 음성 인식'),
        ),
        migrations.CreateModel(
            name='Summarization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('task_id', models.CharField(max_length=32, verbose_name='작업 id')),
                ('generative_ai_model_name', models.CharField(blank=True, max_length=64, null=True, verbose_name='생성형 AI 모델 이름')),
                ('task_start_datetime', models.DateTimeField(blank=True, null=True, verbose_name='작업 시작 시간')),
                ('task_end_datetime', models.DateTimeField(blank=True, null=True, verbose_name='작업 종료 시간')),
                ('task_step_code', models.CharField(blank=True, max_length=32, null=True, verbose_name='작업 단계 코드')),
                ('task_status_code', models.CharField(max_length=16, verbose_name='작업 상태 코드')),
                ('summarization_content', models.TextField(blank=True, null=True, verbose_name='요약 내용')),
                ('minutes_content', models.TextField(blank=True, null=True, verbose_name='회의록 내용')),
                ('action_items', models.JSONField(blank=True, null=True, verbose_name='액션 아이템')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('speech_recognition', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='summarization_set', to='meetings.speechrecognition', verbose_name='음성 인식')),
            ],
            options={
                'verbose_name': '요약',
                'verbose_name_plural': '요약 목록',
                'db_table': 'meetings_summarization',
            },
        ),
        migrations.AddField(
            model_name='recording',
            name='latest_summarization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='meetings.summarization', verbose_name='최근 요약'),
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='id')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='등록일시')),
                ('last_modified_date', models.DateTimeField(auto_now=True, verbose_name='수정일시')),
                ('word', models.CharField(max_length=128, verbose_name='단어')),
                ('score', models.FloatField(verbose_name='점수')),
                ('start_millisecond', models.IntegerField(blank=True, null=True, verbose_name='시작 밀리초')),
                ('end_millisecond', models.IntegerField(blank=True, null=True, verbose_name='종료 밀리초')),
                ('corrected_word', models.CharField(blank=True, max_length=128, null=True, verbose_name='교정된 단어')),
                ('is_correction_removed', models.BooleanField(default=False, verbose_name='교정 삭제 여부')),
                ('created_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='등록자')),
                ('last_modified_user', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='수정자')),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.segment', verbose_name='부분')),
                ('speaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetings.speaker', verbose_name='화자')),
            ],
            options={
                'verbose_name': '단어',
                'verbose_name_plural': '단어 목록',
                'db_table': 'meetings_word',
            },
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['start_datetime', 'end_datetime'], name='idx_meeting_01'),
        ),
        migrations.AlterUniqueTogether(
            name='attendee',
            unique_together={('meeting', 'user')},
        ),
        migrations.AddIndex(
            model_name='speechrecognition',
            index=models.Index(fields=['task_status_code'], name='idx_speech_recognition_01'),
        ),
        migrations.AddIndex(
            model_name='speechrecognition',
            index=models.Index(fields=['task_step_code'], name='idx_speech_recognition_02'),
        ),
        migrations.AddIndex(
            model_name='summarization',
            index=models.Index(fields=['task_status_code'], name='idx_summarization_01'),
        ),
        migrations.AddIndex(
            model_name='word',
            index=django.contrib.postgres.indexes.GinIndex(fields=['word'], name='idx_trgm_word_01', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='word',
            index=django.contrib.postgres.indexes.GinIndex(fields=['corrected_word'], name='idx_trgm_word_02', opclasses=['gin_trgm_ops']),
        ),
    ]
