"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import logging
import os
import re
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(
    DEBUG=(bool, False)
)
environ.Env.read_env(os.path.join(BASE_DIR, '.env'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts.apps.AccountsConfig',
    'django_bootstrap5',
    'django.contrib.humanize',
    'common.apps.CommonConfig',
    'rooms.apps.RoomsConfig',
    'mptt',
    'reservations.apps.ReservationsConfig',
    'meetings.apps.MeetingsConfig',
    'django_q',
    'mathfilters',
    'django.contrib.postgres',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'config.middlewares.HttpMethodOverrideMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    # 'default': env.db('DATABASE_URL', default='sqlite:///db.sqlite3')
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': env('DATABASE_NAME'),
        'USER': env('DATABASE_USER'),
        'PASSWORD': env('DATABASE_PASSWORD'),
        'HOST': env('DATABASE_HOST'),
        'PORT': env('DATABASE_PORT'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ko-kr'

TIME_ZONE = 'Asia/Seoul'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# custom

# STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'staticfiles',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "django.contrib.staticfiles.storage.ManifestStaticFilesStorage",
    },
}

# 수집된 파일이 최종적으로 모이는 곳 (Nginx가 바라보는 곳)
STATIC_ROOT = BASE_DIR / 'static'

LOGIN_REDIRECT_URL = '/'

AUTH_USER_MODEL = 'accounts.User'
AUTHENTICATION_BACKENDS = ['accounts.backends.UserBackend']

# session
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SESSION_COOKIE_AGE = 600
SESSION_SAVE_EVERY_REQUEST = True

# logging
class SkipDjangoQPollingFilter(logging.Filter):
    def filter(self, record):
        msg = str(record.getMessage())
        if "FROM \"django_q_ormq\"" in msg:
            return False
        return True

LOG_DIR = BASE_DIR / 'logs'
if not LOG_DIR.exists():
    LOG_DIR.mkdir(parents=True, exist_ok=True)

LOG_FILENAME = LOG_DIR / f"{os.environ.get('APP_NAME', 'django')}.log"

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'ignore_noise': {
            '()': 'config.filters.IgnoreNoiseRequestsFilter',
        },
        'skip_q_polling': {
            '()': SkipDjangoQPollingFilter,
        },
    },
    'formatters': {
        'django.server': {
            '()': 'django.utils.log.ServerFormatter',
            'format': '[{server_time}][{levelname}] {name} {message}',
            'style': '{',
        },
        'standard': {
            'format': '[%(asctime)s][%(levelname)s] %(name)s: %(message)s',
        },
    },
    'handlers': {
        'console_dev': {
            'level': 'DEBUG',
            'filters': ['require_debug_true', 'skip_q_polling'],
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'console_prod': {
            'level': 'INFO',
            'filters': ['require_debug_false', 'skip_q_polling'],
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'level': 'INFO',
            'filters': ['require_debug_false', 'skip_q_polling'],
            'class': 'logging.handlers.TimedRotatingFileHandler',
            'filename': LOG_FILENAME,
            'when': 'midnight',
            'interval': 1,
            'backupCount': 30,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        },
        'django.server': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'django.server',
            'filters': ['require_debug_true', 'ignore_noise', 'skip_q_polling'],
        },
    },
    'root': {
        'handlers': ['console_dev'] if DEBUG else ['console_prod', 'file'],
        'level': 'DEBUG' if DEBUG else 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['mail_admins', 'file'],
            'level': 'INFO',
            'propagate': True,
        },
        "django.db.backends": {
            "handlers": ['console_dev'] if DEBUG else ['console_prod', 'file'],
            "level": 'DEBUG' if DEBUG else 'INFO',
            'propagate': False,
        },
        'django.server': {
            'handlers': ['django.server'],
            'level': 'INFO',
            'propagate': False,
        },
        "django_q": {
            "handlers": ['console_dev'] if DEBUG else ['console_prod', 'file'],
            "level": "INFO",
            "propagate": False,
        },
    }
}

# login
LOGIN_URL = '/sign-in/'

# media
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# queue
Q_CLUSTER = {
    'name': 'DjangORM',
    'workers': 1,
    'recycle': 1, # 작업 하나 끝날 때마다 프로세스 초기화(메모리 누수 방지)
    'timeout': 7200,
    'retry': 10800,
    'queue_limit': 50,
    "poll": 3,
    'ack_failures': True,
    'orm': 'default',
}

# Hugging Face Token
HF_TOKEN = env('HF_TOKEN')

# Gemini API Key
GEMINI_API_KEY = env('GEMINI_API_KEY')

# upload
FILE_UPLOAD_MAX_MEMORY_SIZE=67108864

# tls
if not DEBUG:
    # 신뢰할 수 있는 Origin 등록
    CSRF_TRUSTED_ORIGINS = [
        f"https://{env.list('ALLOWED_HOSTS')[0]}"
    ]

    # 프록시 헤더 설정 (Nginx가 보낸 HTTPS 신호를 감지)
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

    # 추가적인 보안 세션 설정
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True